### ISSUE TITLE
Can compress/decompress but get an error

### ISSUE THREAD

**Issue by oamidi** [pfalcon/uzlib#20]
Hello,

The attached file (in.dat) does compress to the other (out.zip)
(had to rename the file in.zip to convince the system to accept it)
However, when I decompress (all using example programs given) it 
reports an error.

Both zip and unzip examples work for a multitude of other files.

Thank you
-- Omead

amidi@skeyes.us

[out.zip](https://github.com/pfalcon/uzlib/files/2353604/out.zip)

[in.zip](https://github.com/pfalcon/uzlib/files/2353609/in.zip)

**Comment by pfalcon** [comment]
@oamidi let me know via email that this issue is resolved with the latest master.

I confirmed that attached out.zip (actually out.gz) is broken. But compressin the original in.dat (in.zip here) with tgzip from master, and then uncompressing with tgunzip or standard gzip produces the correct file.

So, closing.

I'm going to release master as 2.9 to have a stable base for comparison.

**Comment by oamidi** [comment]
Hi,

Yes, the latest code I checked out does work properly.

Thank you very much.
-- Omead
